#!/usr/bin/env python3
"""Generate a synthetic class hierarchy for overview-performance checks.

Emits a Turtle ontology of `--roots` independent hierarchies, each
`--depth` levels deep with `--branching` children per node. The default
shape (100 x 2 x 4) yields 1500 classes, comfortably above the 500-node
degradation threshold the overview endpoint exercises.

Usage:
    python tools/gen_big_ontology.py [--out FILE] [--roots N] [--depth N] [--branching N]
"""

from __future__ import annotations

import argparse
from pathlib import Path

HEADER = """# Generated by tools/gen_big_ontology.py - synthetic perf fixture, no external source.
@prefix ex: <http://example.org/big/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
"""


def class_count(roots: int, depth: int, branching: int) -> int:
    """Total nodes across all levels of every hierarchy."""
    return roots * sum(branching**level for level in range(depth))


def emit(out: Path, roots: int, depth: int, branching: int) -> int:
    """Write the ontology; return the number of classes emitted."""
    lines = [HEADER]
    count = 0

    def node_name(root: int, path: tuple[int, ...]) -> str:
        return f"C{root}" + ("".join(f"_{p}" for p in path) if path else "")

    def emit_level(root: int, path: tuple[int, ...], level: int) -> None:
        nonlocal count
        count += 1
        name = node_name(root, path)
        lines.append(f"ex:{name} a owl:Class ;")
        if path:
            parent = node_name(root, path[:-1])
            lines.append(f"    rdfs:subClassOf ex:{parent} ;")
        lines.append(f'    rdfs:label "{name}@root{root}"@en .')
        if level + 1 < depth:
            for child in range(branching):
                emit_level(root, (*path, child), level + 1)

    for root in range(roots):
        emit_level(root, (), 0)

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return count


def main() -> None:
    """Parse args and write the fixture."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("tmp_big_ontology.ttl"))
    parser.add_argument("--roots", type=int, default=100)
    parser.add_argument("--depth", type=int, default=4)
    parser.add_argument("--branching", type=int, default=2)
    args = parser.parse_args()

    total = class_count(args.roots, args.depth, args.branching)
    emitted = emit(args.out, args.roots, args.depth, args.branching)
    print(f"wrote {emitted} classes to {args.out} (planned {total})")


if __name__ == "__main__":
    main()
